version: '3.8'

services:
  backend:
    image: backstage-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: backstage-frontend
    ports:
      - "3000:3000"
    restart: always