# Generated by Django 4.0.5 on 2022-06-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
